### ISSUE TITLE
AttributeError: 'PluginData' object has no attribute 'use_global_registry'

### ISSUE THREAD

**Issue by Sevenyine** [noneplugin/nonebot-plugin-session#10]
nb-cli版本：1.2.2
nonebot_plugin_session版本：0.1.0
启动时报错，报错日志如下：
```
08-11 19:42:51 [ERROR] nonebot | Failed to import "nonebot_plugin_session"
Traceback (most recent call last):
  File "/root/GZbot2/bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_handle/__init__.py", line 25, in <module>
    require("nonebot_plugin_session")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 174, in require
    plugin = load_plugin(name)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 37, in load_plugin
    return manager.load_plugin(module_path)
> File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_session/__init__.py", line 3, in <module>
    from . import adapters, model, saa
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_session/model.py", line 17, in <module>
    plugin_data.use_global_registry()
AttributeError: 'PluginData' object has no attribute 'use_global_registry'
08-11 19:42:51 [ERROR] nonebot | Failed to import "nonebot_plugin_handle"
Traceback (most recent call last):
  File "/root/GZbot2/bot.py", line 28, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 175, in load_all_plugins
    return set(
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/manager.py", line 241, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot_plugin_handle/__init__.py", line 25, in <module>
    require("nonebot_plugin_session")
  File "/root/.cache/pypoetry/virtualenvs/gzbot2-_9hSRCdM-py3.10/lib/python3.10/site-packages/nonebot/plugin/load.py", line 178, in require
    raise RuntimeError(f'Cannot load plugin "{name}"!')
RuntimeError: Cannot load plugin "nonebot_plugin_session"!
```

**Comment by MeetWq** [comment]
检查 `nonebot-plugin-datastore` 版本，需要 `1.1.0` 以上

**Comment by Sevenyine** [comment]
> 检查 `nonebot-plugin-datastore` 版本，需要 `1.1.0` 以上

确实是这个原因！感谢
